/*
The Hot Wand is a 13.56 MHz RF soldering iron, and so the main class-E amplifier is driven by a 13.56 MHz signal
The MCU is driven by a 27.12 MHz crystal as the HSE clock source
and the RF signal is generated by a timer producing a 50% duty cycle square wave at 13.56 MHz
*/

// -----------------------------------------------------------------------------
// Includes
// -----------------------------------------------------------------------------

#include "rfgen.h"

#include "pins.h"
#include "stm32f0xx_hal.h"
#include "tipdetect.h"

// -----------------------------------------------------------------------------
// Configuration
// -----------------------------------------------------------------------------

#define RFGEN_CLOCK_HZ   27120000
#define RFGEN_PWM_PERIOD 1
#define RFGEN_PWM_PULSE  1

/*
 * TIM1 runs directly from the 27.12 MHz crystal.  With PSC = 0 and ARR = 1,
 * one PWM period is two timer ticks: 27.12 MHz / 2 = 13.56 MHz.
 */
_Static_assert(HSE_VALUE == RFGEN_CLOCK_HZ, "RF generator requires a 27.12 MHz external crystal");

// -----------------------------------------------------------------------------
// Globals
// -----------------------------------------------------------------------------

static volatile bool rfgen_clock_fault_logged;
static volatile bool rfgen_emergency_stop_latched;
static volatile bool rfgen_active;

// -----------------------------------------------------------------------------
// Function Prototypes
// -----------------------------------------------------------------------------

static void rfgen_pin_low(void);
static void rfgen_fault(void);

// -----------------------------------------------------------------------------
// Main Flow
// -----------------------------------------------------------------------------

bool rfgen_clock_init(void)
{
    RCC_OscInitTypeDef oscillator_cfg = {0};
    RCC_ClkInitTypeDef clock_cfg      = {0};

    /* Clock initialization must never make the RF output active. */
    rfgen_stop();

    if (rfgen_has_fault())
    {
        return false;
    }

    /* Permit callers such as rfgen_start() to verify an initialized clock. */
    if ((__HAL_RCC_GET_FLAG(RCC_FLAG_HSERDY) != RESET) &&
        (__HAL_RCC_GET_SYSCLK_SOURCE() == RCC_SYSCLKSOURCE_STATUS_HSE))
    {
        HAL_RCC_EnableCSS();
        return true;
    }

    oscillator_cfg.OscillatorType = RCC_OSCILLATORTYPE_HSE;
    oscillator_cfg.HSEState       = RCC_HSE_ON;
    oscillator_cfg.PLL.PLLState   = RCC_PLL_NONE;

    if (HAL_RCC_OscConfig(&oscillator_cfg) != HAL_OK)
    {
        rfgen_fault();
        return false;
    }

    clock_cfg.ClockType      = RCC_CLOCKTYPE_SYSCLK | RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_PCLK1;
    clock_cfg.SYSCLKSource   = RCC_SYSCLKSOURCE_HSE;
    clock_cfg.AHBCLKDivider  = RCC_SYSCLK_DIV1;
    clock_cfg.APB1CLKDivider = RCC_HCLK_DIV1;

    if (HAL_RCC_ClockConfig(&clock_cfg, FLASH_LATENCY_1) != HAL_OK)
    {
        rfgen_fault();
        return false;
    }

    if ((__HAL_RCC_GET_FLAG(RCC_FLAG_HSERDY) == RESET) ||
        (__HAL_RCC_GET_SYSCLK_SOURCE() != RCC_SYSCLKSOURCE_STATUS_HSE))
    {
        rfgen_fault();
        return false;
    }

    HAL_RCC_EnableCSS();
    return true;
}

void rfgen_start(void)
{
    GPIO_InitTypeDef gpio_cfg = {0};
    uint32_t         interrupt_state;

    /* The tip detector and emergency-stop latch independently inhibit RF.
     * Recheck both at the final hardware-enable boundary below. */
    if (rfgen_has_fault() || !rfgen_tip_allows_start())
    {
        rfgen_stop();
        return;
    }

    /*
     * A restart is deliberately a full reconfiguration.  Keep the external
     * circuit disabled while the clock and timer are being rebuilt.
     */
    rfgen_stop();
    if (!rfgen_clock_init())
    {
        return;
    }

    /* Do not let a debugger halt freeze TIM1 on a high PWM half-cycle. The
     * independently running watchdog will reset a halted foreground task. */
    __HAL_RCC_DBGMCU_CLK_ENABLE();
    __HAL_DBGMCU_UNFREEZE_TIM1();

    __HAL_RCC_TIM1_CLK_ENABLE();
    __HAL_RCC_SYSCFG_CLK_ENABLE();
    __HAL_RCC_TIM1_FORCE_RESET();
    __HAL_RCC_TIM1_RELEASE_RESET();

    /*
     * PB1 is TIM1_CH3N on this MCU.  PWM1 makes the complementary output
     * begin low at CNT = 0; CCR = 1 still gives an exact 50 percent duty cycle.
     */
    TIM1->PSC   = 0;
    TIM1->ARR   = RFGEN_PWM_PERIOD;
    TIM1->RCR   = 0;
    TIM1->CCR3  = RFGEN_PWM_PULSE;
    TIM1->CCMR2 = TIM_CCMR2_OC3M_1 | TIM_CCMR2_OC3M_2 | TIM_CCMR2_OC3PE;
    TIM1->CCER  = 0;

    /*
     * Internal lockup and SRAM-parity faults are routed to TIM1's break input.
     * Both run and idle off-states hold the RF output inactive (low).
     */
    TIM1->BDTR = TIM_BDTR_OSSR | TIM_BDTR_OSSI | TIM_BDTR_LOCK_0 | TIM_BDTR_LOCK_1 | TIM_BDTR_BKE | TIM_BDTR_BKP;

    __HAL_SYSCFG_BREAK_LOCKUP_LOCK();
    __HAL_SYSCFG_BREAK_SRAMPARITY_LOCK();

    TIM1->CNT = 0;
    TIM1->EGR = TIM_EGR_UG;
    TIM1->SR  = 0;

    /*
     * Enable CH3N while MOE is clear so TIM1's configured idle state drives
     * low as soon as the pin is changed from GPIO to its alternate function.
     */
    SET_BIT(TIM1->CCER, TIM_CCER_CC3NE);

    gpio_cfg.Pin       = RFGEN_PINn;
    gpio_cfg.Mode      = GPIO_MODE_AF_PP;
    gpio_cfg.Pull      = GPIO_NOPULL;
    gpio_cfg.Speed     = GPIO_SPEED_FREQ_HIGH;
    gpio_cfg.Alternate = GPIO_AF2_TIM1;
    HAL_GPIO_Init(RFGEN_GPIOx, &gpio_cfg);

    /*
     * Close the race where a tip-disconnect ISR stops TIM1 while this function
     * is still configuring it, after which an interrupted start would
     * otherwise resume and re-enable RF.
     */
    interrupt_state = __get_PRIMASK();
    __disable_irq();
    if (rfgen_has_fault() || !rfgen_tip_allows_start())
    {
        rfgen_stop();
        if (interrupt_state == 0)
        {
            __enable_irq();
        }
        return;
    }

    SET_BIT(TIM1->BDTR, TIM_BDTR_MOE);
    SET_BIT(TIM1->CR1, TIM_CR1_CEN);
    rfgen_active = true;

    /* PRIMASK blocks the tip interrupt but cannot block CSS's NMI. Catch a
     * clock fault that arrived during the final timer-enable sequence. */
    if (rfgen_has_fault())
    {
        rfgen_stop();
    }

    if (interrupt_state == 0)
    {
        __enable_irq();
    }
}

void rfgen_stop(void)
{
    rfgen_active = false;

    /*
     * Preload the GPIO latch low, then take ownership away from TIM1.  This
     * avoids the high-impedance stopped state produced by HAL_TIMEx_PWMN_Stop.
     */
    rfgen_pin_low();

    if (__HAL_RCC_TIM1_IS_CLK_ENABLED())
    {
        CLEAR_BIT(TIM1->BDTR, TIM_BDTR_MOE);
        CLEAR_BIT(TIM1->CCER, TIM_CCER_CC3E | TIM_CCER_CC3NE);
        CLEAR_BIT(TIM1->CR1, TIM_CR1_CEN);
    }
}

void rfgen_emergency_stop(void)
{
    /* Disable the timer output before doing the slower GPIO ownership handoff.
     * The latch is checked at both RF-start gates, so an interrupted or later
     * start cannot undo this safety shutdown. */
    rfgen_emergency_stop_latched = true;
    rfgen_active                 = false;

    if (__HAL_RCC_TIM1_IS_CLK_ENABLED())
    {
        CLEAR_BIT(TIM1->BDTR, TIM_BDTR_MOE);
        CLEAR_BIT(TIM1->CCER, TIM_CCER_CC3E | TIM_CCER_CC3NE);
        CLEAR_BIT(TIM1->CR1, TIM_CR1_CEN);
    }

    rfgen_pin_low();
}

// -----------------------------------------------------------------------------
// Getters and Setters
// -----------------------------------------------------------------------------

bool rfgen_has_fault(void)
{
    return rfgen_clock_fault_logged || rfgen_emergency_stop_latched;
}

bool rfgen_has_clock_fault(void)
{
    return rfgen_clock_fault_logged;
}

bool rfgen_is_active(void)
{
    return rfgen_active;
}

// -----------------------------------------------------------------------------
// Supporting Functions
// -----------------------------------------------------------------------------

bool rfgen_tip_allows_start(void)
{
    /*
     * tipdetect_is_qualifying() remains true while the timer is measuring the
     * 300 us debounce interval and while its update interrupt is pending but
     * has not run yet. The timer handler clears the qualifying state before
     * sampling the settled pin and unmasking the next TIP_DET edge.
     *
     * Refusing to start during that interval prevents RF from being enabled
     * while tip presence is uncertain. It also prevents rfgen_clock_init()
     * from changing the timer clock partway through the qualification delay.
     * The main loop retries after UIE clears, so the normal lockout lasts only
     * the debounce interval plus any interrupt latency.
     *
     * This is deliberately fail-closed: if the qualification timer stops, its
     * IRQ is disabled, or its handler never runs, RF restart remains blocked.
     * The timer ISR and tip-detect failure path clear their timer state
     * together; future changes must preserve that invariant or add an explicit
     * timeout/recovery fault.
     */
    if (tipdetect_has_triggered() || tipdetect_is_qualifying())
    {
        return false;
    }

    return HAL_GPIO_ReadPin(TIP_DET_GPIOx, TIP_DET_PINn) == GPIO_PIN_SET;
}

static void rfgen_pin_low(void)
{
    GPIO_InitTypeDef gpio_cfg = {0};

    __HAL_RCC_GPIOB_CLK_ENABLE();
    HAL_GPIO_WritePin(RFGEN_GPIOx, RFGEN_PINn, GPIO_PIN_RESET);

    gpio_cfg.Pin   = RFGEN_PINn;
    gpio_cfg.Mode  = GPIO_MODE_OUTPUT_PP;
    gpio_cfg.Pull  = GPIO_NOPULL;
    gpio_cfg.Speed = GPIO_SPEED_FREQ_HIGH;
    HAL_GPIO_Init(RFGEN_GPIOx, &gpio_cfg);
}

// -----------------------------------------------------------------------------
// Debug / Fault Helpers
// -----------------------------------------------------------------------------

static void rfgen_fault(void)
{
    rfgen_clock_fault_logged = true;
    rfgen_emergency_stop();
}

/*
 * Implementation target for the strong vector shim in interrupt_vectors.S.
 * It is intentionally not part of the public rfgen interface.
 */
void NMI_Handler_Impl(void)
{
    bool css_fault = __HAL_RCC_GET_IT(RCC_IT_CSS) != RESET;

    HAL_RCC_NMI_IRQHandler(); // this will invoke `HAL_RCC_CSSCallback()` and thus `rfgen_fault()` if the `css_fault` is
                              // set

    if (css_fault)
    {
        /* CSS has already changed SYSCLK to HSI; restore the 1 ms HAL tick. */
        SystemCoreClockUpdate();
        HAL_InitTick(TICK_INT_PRIORITY);
    }
}

void HAL_RCC_CSSCallback(void)
{
    rfgen_fault(); // this will signal to the application that a failure occured
}

/*
 * A strong vector shim routes HardFault here. Stop RF on the first fault when
 * the stack is still usable; if this code faults again, the existing Cortex-M0
 * LOCKUP-to-TIM1-break route forces the timer output low in hardware.
 */
void HardFault_Handler_Impl(void)
{
    rfgen_emergency_stop();
    __disable_irq();

    /* Deliberately do not feed IWDG; it provides the eventual system reset. */
    for (;;)
    {
    }
}
