[platformio]
default_envs = seeed_xiao_samd21
include_dir = inc

[env:seeed_xiao_samd21]
platform = atmelsam@8.3.0
board = seeed_xiao
framework = arduino
monitor_speed = 115200
build_flags =
    -D HOT_WAND_TARGET_XIAO_SAMD21=1
    ; Uncomment to generate and print RF tables without touching PWM or DMA.
    ; -D RFGEN_MUTED_DEBUG=1
build_src_filter =
    +<*>
    -<rfgen_rp2040.cpp>

[env:seeed_xiao_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#9c167c6b8aac4f4cfa6d55a0c4e5b848795150c0
board = seeed_xiao_rp2040
framework = arduino
monitor_speed = 115200
build_flags =
    -D HOT_WAND_TARGET_XIAO_RP2040=1
    ; Uncomment to generate and print RF tables without touching PWM or DMA.
    ; -D RFGEN_MUTED_DEBUG=1
build_src_filter =
    +<*>
    -<rfgen_samd21.cpp>

[env:waveshare_rp2040_zero]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#9c167c6b8aac4f4cfa6d55a0c4e5b848795150c0
board = waveshare_rp2040_zero
framework = arduino
monitor_speed = 115200
build_flags =
    -D HOT_WAND_TARGET_WAVESHARE_RP2040_ZERO=1
    ; Uncomment to generate and print RF tables without touching PWM or DMA.
    ; -D RFGEN_MUTED_DEBUG=1
build_src_filter =
    +<*>
    -<rfgen_samd21.cpp>

[env:seeed_xiao_esp32s3]
platform = espressif32@7.0.1
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
build_flags =
    -D HOT_WAND_TARGET_XIAO_ESP32S3=1
    ; Uncomment to generate and print RF tables without touching RMT.
    ; -D RFGEN_MUTED_DEBUG=1
build_src_filter =
    +<*>
    -<rfgen_samd21.cpp>
    -<rfgen_rp2040.cpp>

[env:seeed_xiao_esp32c3]
platform = espressif32@7.0.1
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
build_flags =
    -D HOT_WAND_TARGET_XIAO_ESP32C3=1
    ; Uncomment to generate and print RF tables without touching RMT.
    ; -D RFGEN_MUTED_DEBUG=1
build_src_filter =
    +<*>
    -<rfgen_samd21.cpp>
    -<rfgen_rp2040.cpp>

[env:native_rfgen_tests]
platform = native
extra_scripts = pre:tools/platformio_use_llvm.py
test_framework = unity
test_build_src = true
build_flags =
    -D RFGEN_UNIT_TEST=1
build_src_filter =
    -<*>
    +<rfgen_common.cpp>
