[platformio]
default_envs = stm32f030

[env:stm32f030]
platform = ststm32@19.7.0
board = demo_f030f4
framework = stm32cube
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
build_flags =
    -D HOT_WAND_TARGET_STM32F030=1
lib_deps =
    anurag3301/STM32-SSD1306@1.0.0
