[platformio]
default_envs = stm32f042
include_dir = inc

; It is NOT critical for the code to fit within the flash size of the STM32F030, but it is critical that it fit within the flash size of the STM32F042.  The STM32F042 has a larger flash size, so we can use that as a limit for both targets.
; [env:stm32f030]
; platform = ststm32@19.7.0
; board = demo_f030f4
; framework = stm32cube
; board_build.ldscript = stm32f030f4_nvm.ld
; board_upload.maximum_size = 15360
; upload_protocol = stlink
; debug_tool = stlink
; monitor_speed = 115200
; build_flags =
;     -D HOT_WAND_TARGET_STM32F030=1
;     -D U8X8_WITH_USER_PTR=1
;     -D HSE_VALUE=27120000
;     -flto

[env:stm32f042]
platform = ststm32@19.7.0
board = hotwand_f042f6
framework = stm32cube
board_build.ldscript = stm32f042f6_nvm.ld
board_upload.maximum_size = 31744
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
build_flags =
    -D HOT_WAND_TARGET_STM32F042=1
    -D U8X8_WITH_USER_PTR=1
    -D HSE_VALUE=27120000
    -flto
; Add `-D FAN_STARTUP_OFF_TIME_MS=0` to build_flags when no debugger window is desired.

[env:stm32f042_no_fan_pwm]
extends = env:stm32f042
build_flags =
    ${env:stm32f042.build_flags}
    -D FAN_PWM_ENABLED=0
