[platformio]
default_envs = stm32f030
include_dir = inc

[env:stm32f030]
platform = ststm32@19.7.0
board = demo_f030f4
framework = stm32cube
board_build.ldscript = stm32f030f4_nvm.ld
board_upload.maximum_size = 15360
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
build_flags =
    -D HOT_WAND_TARGET_STM32F030=1
    -D U8X8_WITH_USER_PTR=1
    -D HSE_VALUE=27120000UL
    -flto

[env:stm32f042]
platform = ststm32@19.7.0
board = demo_f042f6
framework = stm32cube
board_build.ldscript = stm32f042f6_nvm.ld
board_upload.maximum_size = 31744
upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200
build_flags =
    -D HOT_WAND_TARGET_STM32F042=1
    -D U8X8_WITH_USER_PTR=1
    -D HSE_VALUE=27120000UL
    -flto
